name: Python CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/src
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: List directory contents (debugging)
        run: |
          ls -R  # Выведет структуру проекта, чтобы проверить наличие тестов

      - name: Set PYTHONPATH
        run: |
          export PYTHONPATH=$(pwd)/src
          python -m unittest discover tests

      - name: Run unit tests
        run: |
          pytest --maxfail=1 --disable-warnings -q 

      - name: Run mypy
        run: |
          mypy src/

      - name: Run black diff check
        run: |
          black --diff --check src/

      - name: Run isort diff check
        run: |
          isort --profile black --check-only --diff src/

      - name: Run flake8
        run: |
          flake8 src/
